cleanup all PR cache instead of just 100 items

diff --git a/.github/workflows/cleanup_cache.yml b/.github/workflows/cleanup_cache.yml
--- a/.github/workflows/cleanup_cache.yml
+++ b/.github/workflows/cleanup_cache.yml
@@ -14,19 +14,29 @@ jobs:
       - name: Cleanup
         run: |
           gh extension install actions/gh-actions-cache
-          
+
           REPO=${{ github.repository }}
           BRANCH="refs/pull/${{ github.event.pull_request.number }}/merge"
 
-          echo "Fetching list of cache key"
-          cacheKeysForPR=$(gh actions-cache list -R $REPO -B $BRANCH -L 100 | cut -f 1 )
-
-          ## Setting this to not fail the workflow while deleting cache keys. 
-          set +e
-          echo "Deleting caches..."
-          for cacheKey in $cacheKeysForPR
+          while true
           do
-              gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
+              echo "Fetching list of cache key"
+              cacheKeysForPR=$(gh actions-cache list -R $REPO -B $BRANCH -L 100 | cut -f 1 )
+
+              if [ -z "$(printf "%s" "$cacheKeysForPR")" ]
+              then
+                  echo "No caches to delete"
+                  break
+              fi
+
+              ## Setting this to not fail the workflow while deleting cache keys. 
+              set +e
+              for cacheKey in $cacheKeysForPR
+              do
+                  echo Deleting $cacheKey
+                  gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
+              done
+              set -e
           done
           echo "Done"
         env:
